#pragma once
enum DirectUIAttribute
{
	DUI_MOUSE_REMAINON = 0 ,
	DUI_MOUSE_LEFT_CLICK = 1,
	DUI_MOUSE_MOVE = 2,
	DUI_MOUSE_RIGHT_CLICK = 3,
	DUI_MOUSE_LEFT_DOUBLE_CLICK = 4,
	DUI_MOUSE_RIGHT_DOUBLE_CLICK = 5,
	DUI_MOUSE_LEFT_CLICK_REMAIN_MOVE = 6
};