#pragma once
enum DirectUIAttribute
{
	DUI_MOUSE_REMAINON = 0 ,
	DUI_MOUSE_LEFT_CLICK_DOWN = 1,
	DUI_MOUSE_LEFT_CLICK_UP = 2,
	DUI_MOUSE_MOVE = 3,
	DUI_MOUSE_RIGHT_CLICK = 4,
	DUI_MOUSE_LEFT_DOUBLE_CLICK = 5,
	DUI_MOUSE_RIGHT_DOUBLE_CLICK = 6,
	DUI_MOUSE_LEFT_CLICK_REMAIN_MOVE = 7
};